# Generated by Django 3.2.5 on 2021-07-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dod', models.DateField(verbose_name='Date Of Delivery')),
                ('tod', models.CharField(choices=[(' ', 'No Time Of Day'), ('s', 'Sunrise'), ('b', 'Breakfast'), ('x', 'Morning'), ('y', 'Afternoon'), ('z', 'Evening')], default=' ', max_length=1, verbose_name='Time Of Day')),
                ('dow', models.CharField(choices=[('su', 'Sunday'), ('mo', 'Monday'), ('tu', 'Tuesday'), ('we', 'Wednesday'), ('th', 'Thursday'), ('fr', 'Friday'), ('sa', 'Saturday')], default='su', max_length=2, verbose_name='Day Of Week')),
                ('title', models.CharField(max_length=64, verbose_name='Document Title')),
                ('descriptor', models.CharField(max_length=120, verbose_name='Descriptor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('cur_assign_id', models.IntegerField(blank=True, null=True, verbose_name='current Assignment ID')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.CharField(max_length=3, verbose_name='Language')),
                ('tran_title', models.CharField(max_length=70, verbose_name='Translated title')),
                ('descrip', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('blkc', models.IntegerField(verbose_name='Block count')),
                ('subc', models.IntegerField(verbose_name='Sub-block count')),
                ('senc', models.IntegerField(verbose_name='Sentence count')),
                ('xcrip', models.CharField(choices=[('A', 'Andes'), ('M', 'Mamalis')], default='A', max_length=1, verbose_name='Transcription')),
                ('li', models.BooleanField(verbose_name='Lookup imported (eng) / translate contributions randomized (oth)')),
                ('pubdate', models.DateField(verbose_name='Publication date')),
                ('version', models.CharField(max_length=10, verbose_name='Version')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tranai.document')),
                ('eng_tran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tranai.translation')),
            ],
        ),
    ]
