# Generated by Django 3.2.5 on 2021-07-05 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dod', models.DateTimeField(verbose_name='Date of Delivery')),
                ('tod', models.CharField(max_length=60, verbose_name='Time of Day')),
                ('dow', models.CharField(max_length=60, verbose_name='Day of Week')),
                ('title', models.CharField(max_length=120, verbose_name='Document Title')),
                ('descriptor', models.CharField(max_length=120, verbose_name='Descriptor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('admin', models.BooleanField(default=False, verbose_name='admin')),
                ('cur_assign_id', models.IntegerField(blank=True, null=True, verbose_name='cur_assign_id')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.CharField(max_length=3, verbose_name='lan')),
                ('tran_title', models.CharField(max_length=300, verbose_name='tran_title')),
                ('descrip', models.TextField(max_length=300, verbose_name='descrip')),
                ('blkc', models.CharField(max_length=300, verbose_name='blkc')),
                ('subc', models.CharField(max_length=300, verbose_name='subc')),
                ('senc', models.CharField(max_length=300, verbose_name='senc')),
                ('xcrip', models.CharField(max_length=1, verbose_name='xcrip')),
                ('li', models.CharField(max_length=300, verbose_name='li')),
                ('pubdate', models.CharField(max_length=300, verbose_name='pubdate')),
                ('version', models.CharField(max_length=300, verbose_name='version')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tranai.document')),
            ],
        ),
    ]
