# Generated by Django 3.2.5 on 2021-07-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cur_assign_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='current assignment id'),
        ),
    ]
