# Generated by Django 3.2.5 on 2021-07-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranai', '0003_alter_translation_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='version',
            field=models.CharField(max_length=20, verbose_name='Version'),
        ),
    ]
