# Generated by Django 3.2.5 on 2021-07-09 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tranai', '0004_alter_translation_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tranai.document'),
        ),
    ]
