# Generated by Django 3.2.5 on 2021-07-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tranai', '0004_alter_user_cur_assign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, verbose_name='Username'),
        ),
    ]
