# Generated by Django 3.2.5 on 2021-07-14 18:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tranai', '0005_alter_translation_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tod',
            field=models.CharField(choices=[('n', 'No Time Of Day'), ('s', 'Sunrise'), ('b', 'Breakfast'), ('x', 'Morning'), ('y', 'Afternoon'), ('z', 'Evening')], default='n', max_length=1, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1)], verbose_name='Time Of Day'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EP', 'English Provider'), ('EE', 'English Editor'), ('NT', 'No Translator'), ('MT', 'Machine Translator'), ('HT', 'Human Translator'), ('TE', 'Translation Editor'), ('SE', 'Scripture Editor'), ('PE', 'Poetry Editor'), ('CE', 'Chief Editor'), ('LA', 'Language Administrator')], default='TE', max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)], verbose_name='Role')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('place', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Place')),
                ('ci', models.BooleanField(default=False, verbose_name='Content imported')),
                ('status', models.CharField(choices=[('ip', 'In Process'), ('cd', 'Completed'), ('te', 'TE editing'), ('ce', 'CE editing'), ('qe', 'QE editing'), ('pg', 'Publishing'), ('pd', 'Published'), ('pr', 'Pruned')], default='ip', max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)], verbose_name='Status')),
                ('ccs', models.IntegerField(blank=True, null=True, verbose_name='Final Create additions')),
                ('ccs_k', models.IntegerField(blank=True, null=True, verbose_name='- by klearing')),
                ('ccs_m', models.IntegerField(blank=True, null=True, verbose_name='- by modding')),
                ('vcs', models.IntegerField(blank=True, null=True, verbose_name='Final Vote additions')),
                ('vcs_a', models.IntegerField(blank=True, null=True, verbose_name='- by accepting')),
                ('vcs_c', models.IntegerField(blank=True, null=True, verbose_name='- by creating')),
                ('vcs_t', models.IntegerField(blank=True, null=True, verbose_name='- by topping')),
                ('vcs_p', models.IntegerField(blank=True, null=True, verbose_name='- by picking')),
                ('ct', models.IntegerField(blank=True, null=True, verbose_name='Final Create time (s)')),
                ('vt', models.IntegerField(blank=True, null=True, verbose_name='Final Vote time (s)')),
                ('majtes', models.IntegerField(blank=True, null=True, verbose_name='Final Majority Top Changes')),
                ('tietes', models.IntegerField(blank=True, null=True, verbose_name='Final Tie Top Changes')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Notes')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='tranai.translation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='tranai.user')),
            ],
        ),
    ]
